### ISSUE TITLE
Console Error

### ISSUE THREAD

**Issue by drakenx** [CoachLuck/EssentialServer#4]
[EssentialServer] Enabling EssentialServer v1.2.8
[09:41:22] [Server thread/ERROR]: Could not call method 'public static org.bukkit.Location org.bukkit.Location.deserialize(java.util.Map)' of class org.bukkit.Location for deserialization
java.lang.IllegalArgumentException: unknown world
        at org.bukkit.Location.deserialize(Location.java:668) ~[spigot-1.16.3.jar:git-Spigot-988b411-1f4693a]
        at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_261]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_261]
        at org.bukkit.configuration.serialization.ConfigurationSerialization.deserializeViaMethod(ConfigurationSerialization.java:85) ~[spigot-1.16.3.jar:git-Spigot-988b411-1f4693a]
        at org.bukkit.configuration.serialization.ConfigurationSerialization.deserialize(ConfigurationSerialization.java:127) ~[spigot-1.16.3.jar:git-Spigot-988b411-1f4693a]
        at org.bukkit.configuration.serialization.ConfigurationSerialization.deserializeObject(ConfigurationSerialization.java:207) ~[spigot-1.16.3.jar:git-Spigot-988b411-1f4693a]
        at org.bukkit.configuration.file.YamlConstructor$ConstructCustomObject.construct(YamlConstructor.java:37) ~[spigot-1.16.3.jar:git-Spigot-988b411-1f4693a]
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:230) ~[spigot-1.16.3.jar:git-Spigot-988b411-1f4693a]
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:219) ~[spigot-1.16.3.jar:git-Spigot-988b411-1f4693a]
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping2ndStep(BaseConstructor.java:479) ~[spigot-1.16.3.jar:git-Spigot-988b411-1f4693a]
        at org.yaml.snakeyaml.constructor.SafeConstructor.constructMapping2ndStep(SafeConstructor.java:190) ~[spigot-1.16.3.jar:git-Spigot-988b411-1f4693a]
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping(BaseConstructor.java:460) ~[spigot-1.16.3.jar:git-Spigot-988b411-1f4693a]
        at org.yaml.snakeyaml.constructor.SafeConstructor$ConstructYamlMap.construct(SafeConstructor.java:556) ~[spigot-1.16.3.jar:git-Spigot-988b411-1f4693a]
        at org.bukkit.configuration.file.YamlConstructor$ConstructCustomObject.construct(YamlConstructor.java:28) ~[spigot-1.16.3.jar:git-Spigot-988b411-1f4693a]
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:230) ~[spigot-1.16.3.jar:git-Spigot-988b411-1f4693a]
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:219) ~[spigot-1.16.3.jar:git-Spigot-988b411-1f4693a]
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping2ndStep(BaseConstructor.java:479) ~[spigot-1.16.3.jar:git-Spigot-988b411-1f4693a]
        at org.yaml.snakeyaml.constructor.SafeConstructor.constructMapping2ndStep(SafeConstructor.java:190) ~[spigot-1.16.3.jar:git-Spigot-988b411-1f4693a]
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping(BaseConstructor.java:460) ~[spigot-1.16.3.jar:git-Spigot-988b411-1f4693a]
        at org.yaml.snakeyaml.constructor.SafeConstructor$ConstructYamlMap.construct(SafeConstructor.java:556) ~[spigot-1.16.3.jar:git-Spigot-988b411-1f4693a]
        at org.bukkit.configuration.file.YamlConstructor$ConstructCustomObject.construct(YamlConstructor.java:28) ~[spigot-1.16.3.jar:git-Spigot-988b411-1f4693a]
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:230) ~[spigot-1.16.3.jar:git-Spigot-988b411-1f4693a]
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:219) ~[spigot-1.16.3.jar:git-Spigot-988b411-1f4693a]
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping2ndStep(BaseConstructor.java:479) ~[spigot-1.16.3.jar:git-Spigot-988b411-1f4693a]
        at org.yaml.snakeyaml.constructor.SafeConstructor.constructMapping2ndStep(SafeConstructor.java:190) ~[spigot-1.16.3.jar:git-Spigot-988b411-1f4693a]
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping(BaseConstructor.java:460) ~[spigot-1.16.3.jar:git-Spigot-988b411-1f4693a]
        at org.yaml.snakeyaml.constructor.SafeConstructor$ConstructYamlMap.construct(SafeConstructor.java:556) ~[spigot-1.16.3.jar:git-Spigot-988b411-1f4693a]
        at org.bukkit.configuration.file.YamlConstructor$ConstructCustomObject.construct(YamlConstructor.java:28) ~[spigot-1.16.3.jar:git-Spigot-988b411-1f4693a]
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:230) ~[spigot-1.16.3.jar:git-Spigot-988b411-1f4693a]
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:219) ~[spigot-1.16.3.jar:git-Spigot-988b411-1f4693a]
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructDocument(BaseConstructor.java:173) ~[spigot-1.16.3.jar:git-Spigot-988b411-1f4693a]
        at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:157) ~[spigot-1.16.3.jar:git-Spigot-988b411-1f4693a]
        at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:472) ~[spigot-1.16.3.jar:git-Spigot-988b411-1f4693a]
        at org.yaml.snakeyaml.Yaml.load(Yaml.java:398) ~[spigot-1.16.3.jar:git-Spigot-988b411-1f4693a]
        at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:57) ~[spigot-1.16.3.jar:git-Spigot-988b411-1f4693a]
        at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:160) ~[spigot-1.16.3.jar:git-Spigot-988b411-1f4693a]
        at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:128) ~[spigot-1.16.3.jar:git-Spigot-988b411-1f4693a]
        at org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(YamlConfiguration.java:186) ~[spigot-1.16.3.jar:git-Spigot-988b411-1f4693a]
        at io.github.coachluck.warps.WarpFile.<init>(WarpFile.java:53) ~[?:?]
        at io.github.coachluck.EssentialServer.createDirectories(EssentialServer.java:181) ~[?:?]
        at io.github.coachluck.EssentialServer.onEnable(EssentialServer.java:68) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[spigot-1.16.3.jar:git-Spigot-988b411-1f4693a]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:351) ~[spigot-1.16.3.jar:git-Spigot-988b411-1f4693a]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[spigot-1.16.3.jar:git-Spigot-988b411-1f4693a]
        at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugin(CraftServer.java:494) ~[spigot-1.16.3.jar:git-Spigot-988b411-1f4693a]
        at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugins(CraftServer.java:408) ~[spigot-1.16.3.jar:git-Spigot-988b411-1f4693a]
        at net.minecraft.server.v1_16_R2.MinecraftServer.loadWorld(MinecraftServer.java:435) ~[spigot-1.16.3.jar:git-Spigot-988b411-1f4693a]
        at net.minecraft.server.v1_16_R2.DedicatedServer.init(DedicatedServer.java:216) ~[spigot-1.16.3.jar:git-Spigot-988b411-1f4693a]
        at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:808) ~[spigot-1.16.3.jar:git-Spigot-988b411-1f4693a]
        at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[spigot-1.16.3.jar:git-Spigot-988b411-1f4693a]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_261]

Plugin still seems functional

**Comment by CoachLuck** [comment]
Hey do you mind joining my discord via this [link](https://discord.gg/ERmbF2z) and I could help and discuss this further.

**Comment by CoachLuck** [comment]
The problem is that it is currently trying to load a warp from an unknown world. Have your recently deleted a world?

**Comment by drakenx** [comment]
That was it CouchLuck, I have two worlds connected to each other with another plugin it just wasn't recognizing that second world. deleted the one warp I had on it and the error went away. Thanks!

**Comment by CoachLuck** [comment]
Glad that it was an easy fix :)
